
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 06 12:04:54 CEST 2011
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int empty = 36;
  public static final int MULT = 33;
  public static final int LPAREN = 20;
  public static final int INT = 12;
  public static final int MINUS = 32;
  public static final int STATIC = 35;
  public static final int RPAREN = 21;
  public static final int NOT = 28;
  public static final int SEMICOLON = 24;
  public static final int LT = 30;
  public static final int COMMA = 25;
  public static final int CLASS = 3;
  public static final int ANDAND = 29;
  public static final int PLUS = 31;
  public static final int IF = 14;
  public static final int THIS = 6;
  public static final int DOT = 26;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RETURN = 4;
  public static final int TRUE = 11;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int VOID = 8;
  public static final int EQ = 27;
  public static final int LBRACK = 22;
  public static final int LBRACE = 18;
  public static final int ELSE = 15;
  public static final int RBRACK = 23;
  public static final int WHILE = 16;
  public static final int PUBLIC = 2;
  public static final int RBRACE = 19;
  public static final int STRING = 13;
  public static final int FALSE = 10;
  public static final int PRINT = 17;
  public static final int LENGTH = 5;
  public static final int IDENTIFIER = 34;
}

